language: perl
perl:
  - "5.8"
  - "5.8-thr"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.20-thr"
  - "blead"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
  - "echo 'use Test::More skip_all => q[skipping];' > xt/release/changes_has_content.t"
  - "echo 'use Test::More skip_all => q[skipping];' > xt/release/kwalitee.t"
  - cpan-install Test::Portability::Files Test::Mojibake Test::EOL Test::Pod::No404s Test::MinimumVersion PadWalker
